# Generated by Django 3.0 on 2019-12-23 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rss',
            name='add_to',
            field=models.DateField(auto_now=True, verbose_name='data creazione'),
        ),
        migrations.AddField(
            model_name='rss',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Utente', to=settings.AUTH_USER_MODEL),
        ),
    ]
