# Generated by Django 3.0 on 2019-12-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_auto_20191223_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rss',
            options={'verbose_name': 'Rss', 'verbose_name_plural': 'Rss'},
        ),
        migrations.RemoveField(
            model_name='rss',
            name='add_to',
        ),
        migrations.AddField(
            model_name='rss',
            name='added_on',
            field=models.DateField(auto_now=True, verbose_name='Aggiunto il '),
        ),
    ]
