# Generated by Django 3.0 on 2020-01-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0004_auto_20191223_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rss',
            options={},
        ),
        migrations.RemoveField(
            model_name='rss',
            name='added_on',
        ),
        migrations.AlterField(
            model_name='rss',
            name='link',
            field=models.EmailField(max_length=256, verbose_name='link'),
        ),
    ]
