# Generated by Django 3.0 on 2020-01-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0005_auto_20200103_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rss',
            options={'verbose_name': 'RSS', 'verbose_name_plural': 'RSS'},
        ),
    ]
