# Generated by Django 3.0 on 2020-01-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0006_auto_20200103_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rss',
            name='link',
            field=models.URLField(max_length=256, verbose_name='link'),
        ),
    ]
